//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GOST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOST()
        {
            this.PRIJATELJIs = new HashSet<PRIJATELJI>();
            this.PRIJATELJIs1 = new HashSet<PRIJATELJI>();
            this.REZERVACIJAs = new HashSet<REZERVACIJA>();
        }
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Obavezno je uneti mail.")]
        [System.ComponentModel.DisplayName("Email")]
        public string EMAIL_GOSTA { get; set; }
        [System.ComponentModel.DisplayName("Lozinka")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Obavezno je uneti lozinku.")]
        public string PASS_GOSTA { get; set; }
        [System.ComponentModel.DisplayName("Potvrdi lozinku")]
        [Compare("PASS_GOSTA", ErrorMessage = "Lozinke se ne poklapaju")]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Obavezno je potvrditi lozinku.")]
        public string CPASS_GOSTA { get; set; }
        [System.ComponentModel.DisplayName("Ime")]
        public string IME_GOSTA { get; set; }
        [System.ComponentModel.DisplayName("Prezime")]
        public string PREZIME_GOSTA { get; set; }
        public string POL_GOSTA { get; set; }
        public bool MAIL_POTVRA { get; set; }        
        public byte[] SLIKA { get; set; }    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIJATELJI> PRIJATELJIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIJATELJI> PRIJATELJIs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REZERVACIJA> REZERVACIJAs { get; set; }
    }
}
