//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JELOVNIK
    {
        [System.ComponentModel.DisplayName("ID restorana")]
        public string ID_RESTORANA { get; set; }
        [System.ComponentModel.DisplayName("ID jela")]
        public string ID_JELA { get; set; }
        [System.ComponentModel.DisplayName("Naziv jela")]
        public string NAZIV_JELA { get; set; }
        [System.ComponentModel.DisplayName("Opis jela")]
        public string OPIS { get; set; }
        [System.ComponentModel.DisplayName("Cena jela")]
        public decimal CENA_JELA { get; set; }
    
        public virtual RESTORAN RESTORAN { get; set; }
    }
}
