//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RezervacijeDBEntities : DbContext
    {
        public RezervacijeDBEntities()
            : base("name=RezervacijeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<GOST> GOSTs { get; set; }
        public virtual DbSet<JELOVNIK> JELOVNIKs { get; set; }
        public virtual DbSet<MENADZER> MENADZERs { get; set; }
        public virtual DbSet<RESTORAN> RESTORANs { get; set; }
        public virtual DbSet<REZERVACIJA> REZERVACIJAs { get; set; }
        public virtual DbSet<STO> STOes { get; set; }
        public virtual DbSet<PRIJATELJI> PRIJATELJIs { get; set; }
    }
}
