//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RESTORAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESTORAN()
        {
            this.JELOVNIKs = new HashSet<JELOVNIK>();
            this.MENADZERs = new HashSet<MENADZER>();
            this.STOes = new HashSet<STO>();
        }

        [System.ComponentModel.DisplayName("ID Restorana")]
        public string ID_RESTORANA { get; set; }

        [System.ComponentModel.DisplayName("Naziv restorana")]
        public string NAZIV_RESTORANA { get; set; }

        [System.ComponentModel.DisplayName("Adresa restorana")]
        public string ADRESA_RESTORANA { get; set; }

        [System.ComponentModel.DisplayName("Email restorana")]
        public string MAIL_RESTORANA { get; set; }

        [DataType(DataType.PhoneNumber)]
        [System.ComponentModel.DisplayName("Telefon restorana")]
        public string TELEFON_RESTORANA { get; set; }

        [DataType(DataType.PhoneNumber)]
        [System.ComponentModel.DisplayName("Prosecna ocena")]
        public float PROSECNA_OCENA { get; set; }

        [System.ComponentModel.DisplayName("Opis restorana")]
        public string OPIS_RESTPRANA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JELOVNIK> JELOVNIKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENADZER> MENADZERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STO> STOes { get; set; }
    }
}
