//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZERVACIJA
    {
        public int ID { get; set; }
        public string EMAIL_GOSTA { get; set; }
        public string ID_RESTORANA { get; set; }
        public string ID_STOLA { get; set; }
        public int OCENA { get; set; }
        public System.DateTime VREME_DOLASKA { get; set; }
        public System.DateTime VREME_ODLASKA { get; set; }
    
        public virtual GOST GOST { get; set; }
        public virtual STO STO { get; set; }
    }
}
